### ISSUE TITLE
[v6] Impossible to display something on android

### ISSUE THREAD

**Issue by christophemenager** [chramos/react-native-skeleton-placeholder#143]
```
   <Box flex={1} justifyContent="center" alignItems="center">
        <SkeletonPlaceholder
          borderRadius={SPACINGS.l}
          backgroundColor={COLORS.green}
          highlightColor={COLORS.green}
        >
          <SkeletonPlaceholder.Item width={300} height={300} />
        </SkeletonPlaceholder>
      </Box>
```

Using this code:
- It works on iOS
- It is not displayed on android at all

I am using latest beta (v7) and expo.
"react-native-svg": "15.11.2",
"react-native-reanimated": "3.16.7",

**Comment by chramos** [comment]
Can you  provide which device you have tested?
I did test on few emulators and it worked

**Comment by christophemenager** [comment]
@chramos it's a physical device: Xiaomi 12T

**Comment by chramos** [comment]
@christophemenager, thank you!
I'll check it and I back to you soon

**Comment by chramos** [comment]
@christophemenager, I tried on my device: Xiaomi Poco X3 and it seems working!
I see an issue that idk if it's related to the new architecture, but the onLayout function was return 0 for x and y.
I fixed the issue and I'll deploy a beta.8.
can you please try it out?

**Comment by chramos** [comment]
<img width="1113" alt="Image" src="https://github.com/user-attachments/assets/fe9241ce-9c38-46db-8f8a-3f7193ad5789" />

**Comment by Cesar02dd** [comment]
Hey @chramos ! This issue still persists for me on beta 8.

I'm experiencing strange behavior (view images) with the Skeleton Placeholder on Android (possibly related to the new architecture?). Components are sometimes only partially rendered and in some cases dont render at all. It seems like the container's dimensions are not being properly calculated.

I created a simple expo app using the code from the readme file to verify if the issue was with my project or the package itself, and it still occurs.

I am using latest beta (v8) and expo.
"expo": "~52.0.42",
"react-native-svg": "^15.11.2",
"react-native-reanimated": "~3.16.1",

I tested with (same issues in all devices):
- my physical device: Samsung S23 - API 34
- virtual device: Google Pixel 7A - API 35
- virtual device: Google Pixel 7A - API 31

and in the override section of the package.json (just because I had compiler issues):

"overrides": {
    "react-native-skeleton-placeholder": {
      "react": "18.3.1",
      "react-native-svg": "^15.11.2"
    }
  }

NOTE: Last week or so everything was working with beta 7 and suddenly stopped working. When testing try to play with different components inside the Skeleton Placeholder (for example, removing the Text component in the example code)

Code that is inside app/(tabs)/index.tsx: 
```javascript
import React, { useState, useEffect } from "react";
import { View, Text, StyleSheet, Image } from "react-native";
import SkeletonPlaceholder from "react-native-skeleton-placeholder";

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <SkeletonPlaceholder borderRadius={4}>
        <View style={{flexDirection: 'row', gap: 16, alignItems: 'center'}}>
          <View style={{width: 60, height: 60, borderRadius: 50}} />
          <View style={{gap: 6}}>
            <View style={{width: 120, height: 20}} />
            <View style={{width: 80, height: 20}} />
          </View>
          <View style={{gap: 16}}>
            <Image
              source={{uri: 'https://picsum.photos/200/300'}}
              style={{width: 200, height: 200}}
            />
            <Text style={{fontSize: 24}}>Do aute nulla aliquip deserunt ex est dolor</Text>
          </View>
        </View>
      </SkeletonPlaceholder>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    paddingTop: 50,
  },
});
```

<img src="https://github.com/user-attachments/assets/c20619cd-c803-40b0-9ab3-213dc8fadbcf" width="300" />

<img src="https://github.com/user-attachments/assets/c7d1741a-190a-4a6e-a096-86a96605b0e3" width="300" />

<img src="https://github.com/user-attachments/assets/0af9c73c-fcae-410f-bca6-d5b40abc9858" width="300" />

**Comment by chramos** [comment]
Hi @Cesar02dd, thank you for sharing.
I'll take a look on it this weekend

**Comment by chramos** [comment]
hi guys, I think I found the main issue on android...

I manage to replicate the issue with the @Cesar02dd sample code, and the solution for his case is to remove the style from the parent and place in the first view inside the SkeletonPlaceholder tag

```js
<SkeletonPlaceholder ... >
    <View style={styles.container}>
        ...
    </View>
</SkeletonPlaceholder>
```

I'll try to fix the main issue
