### ISSUE TITLE
A big performance issue before load

### ISSUE THREAD

**Issue by ugrdursun** [chramos/react-native-skeleton-placeholder#55]
Firstly, thanks for this beautiful library,

But I am having a massive delay like 4-5 seconds before the page with skeleton loads.

RN 0.61.5
Library 4.0
MaskedView@latest

 Any suggestion ?

**Comment by junioroga** [comment]
Hi @ugrdursun, your problem only occurs on Android? because I also have this problem, but only on android.

There is a pull request created by @andreialect that is open for performance correction, but I am not able to test it to see if it fixed the issue.

https://github.com/chramos/react-native-skeleton-placeholder/pull/54

@andreialecu can you help us?
I tried to use your fork in my project, but it gives error in node modules

**Comment by andreialecu** [comment]
You should be able to use the PR via the instructions in this comment: https://github.com/chramos/react-native-skeleton-placeholder/issues/53#issuecomment-867516147

**Comment by junioroga** [comment]
@andreialecu It worked! Solved the performance issue! But to work your PR I had to change the path of main in package.json
from lib/SkeletonPlaceholder.js to src/SkeletonPlaceholder.tsx

**Comment by chramos** [comment]
I merged the @andreialecu code... 
check if it solve the performance issue ;D

**Comment by Sargnec** [comment]
> I merged the @andreialecu code...
> check if it solve the performance issue ;D
Do I have to do another thing beside upgrading to 5.0.0? Because looks like mine still delays the animation in android. Havent tried on Ios yet

**Comment by ugrdursun** [comment]
> I merged the @andreialecu code...
> check if it solve the performance issue ;D

Hello, Unfortunately upgrading 5.0.0 did not solve the issue, also not even reduced delay duration :(

**Comment by farazirfan47** [comment]
Same heppning with me
