### ISSUE TITLE
Deprecated @react-native-masked-view/masked-view

### ISSUE THREAD

**Issue by gaabrielricci** [chramos/react-native-skeleton-placeholder#98]
@react-native-masked-view/masked-view
This lib was chagend to:
@react-native-community/masked-view

const masked_view_1 = __importDefault(require("@react-native-masked-view/masked-view"));
and this import is causing an error on compile

const masked_view_1 = __importDefault(require("@react-native-community/masked-view"));
i change manually the require in app\node_modules\react-native-skeleton-placeholder\lib\skeleton-placeholder.js and solve the problem.

**Comment by VhoraAbdulrauf** [comment]
can anyone solve this with proper solution ?

**Comment by chramos** [comment]
it is already solved in the latest version

**Comment by gaabrielricci** [comment]
thankyou

**Comment by gaabrielricci** [comment]
@chramos, 
I deleted the node_modules folder, did a yarn install, npm install and the problem was not occurring. But today, I uninstalled the app and installed it again and the error came back.

![Screenshot_1666869848](https://user-images.githubusercontent.com/27814206/198273037-ae1d7cb3-d177-4953-b43f-fa6b69aadb95.png)
![Captura de tela 2022-10-27 082523](https://user-images.githubusercontent.com/27814206/198273041-9f59fe76-0697-48bb-9f10-de526f59e53c.png)
![Captura de tela 2022-10-27 082922](https://user-images.githubusercontent.com/27814206/198273044-028ccb2b-b341-444f-8a8b-663f39a6c74a.png)
